# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

sudo: required

matrix:
  include:
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  - php: 5.6
    env: WP_TRAVISCI=travis:phpvalidate
  - php: hhvm
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  allow_failures:
  - php: hhvm
  fast_finish: true

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

before_install:
  # set up WP install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # prepare for running the tests
  - cd $TRAVIS_BUILD_DIR
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version
  - grunt --version

before_script:
  # Setup Coveralls
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpvalidate" ]] ; then
      composer self-update
      composer install --no-interaction
    fi
script:
  - grunt $WP_TRAVISCI

git:
  depth: 1

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
