language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  - php: 5.6
    env: WP_TRAVISCI=travis:phpvalidate
  - php: 5.5
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.4
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.3
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.2
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: hhvm
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  allow_failures:
  - php: hhvm
  fast_finish: true

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
